key     ::=  string | number | name
value   ::=  string | number | name

name   ::=  "@" name
prefix  ::=  "PREFIX"
timeout ::=  "TIMEOUT" uint64

add     ::=  "ADD" key "VALUE" value [timeout]
get     ::=  "GET" [prefix] key [timeout]
update  ::=  "UPDATE" [prefix] key "VALUE" value [timeout]
delete  ::=  "DELETE" [prefix] key [timeout]

stat    ::=  add | get | update | delete